### ISSUE TITLE
Upgrade to GDAL 2.0

### ISSUE THREAD

**Issue by shawnlaffan** [shawnlaffan/biodiverse#573]
GDAL 2.0 is out, as is the Geo::GDAL module.  

It works under Linux, but need to get it working on the other platforms.

**Comment by andersonku** [comment]
Installation of Geo::GDAL 2.01/2.02 on OSX failed because of test failure
Macport installs GDAL 2.02 while CPAN Geo::GDAL only supports 2.01
Following the instruction from:
https://trac.osgeo.org/gdal/wiki/GdalOgrInPerl

```
export PERL_GDAL_NO_VERSION_CHECK=1
export PERL_GDAL_CONFIG=/opt/local/bin/gdal-config
# both cpanm and the following manual step result the same result
# cpanm Geo::GDAL
cd $GDAL checkout
./configure
cd swig/perl
make generate
perl Makefile.pl
make
make test

t/03.t .... 
ok 1 - use Geo::GDAL;
RuntimeError /vsimem/test.gtiff, band 1: SetCategoryNames() not supported for this dataset. at /Users/xsoteria/Downloads/gdal-2.0.2/swig/perl/blib/lib/Geo/GDAL.pm line 1456.
1..1
# Looks like your test exited with 2 just after 1.
Dubious, test returned 2 (wstat 512, 0x200)
```

Looks like this part of test failed:
`my $dataset = Geo::GDAL::Driver('GTiff')->Create(Name => '/vsimem/test.gtiff', Width => 4, Height => 6);
my $band = $dataset->Band;`

Created a ticket for GDAL
https://trac.osgeo.org/gdal/ticket/6418#ticket

**Comment by shawnlaffan** [comment]
A working version of GDAL 2.x on Mac OSX has now been generated.  Need to update the installation instructions to match.

**Comment by shawnlaffan** [comment]
To do:
- [X] Get it working on Windows
- [ ] Update windows installation instructions (waiting on Gtk2 updates before official shift to 5.24)
- [ ] Update OSX installation instructions

These are all for Shawn to do.

**Comment by shawnlaffan** [comment]
Mark as fixed
